# Generated by Django 2.1.2 on 2018-12-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_auto_20181210_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
