# Generated by Django 2.1.2 on 2018-12-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0005_auto_20181210_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.TextField(max_length=2000),
        ),
    ]
